<?php require('template/header.phtml') ?>

    <h3>Friends</h3>
<p>Here you can see your current friends and unfriend them if you like.</p>

<?php if (!isset($_SESSION["login"])){
        //This message displays if user logs out on this page
    echo '<p> Oops! you have no friends, please log in or create an account to see your friendships.</p>';
} else
{
    //Loop to display selected fields from user's data from data set
    foreach ($view->friendDataSet as $friendData) {
        echo '<div class = "row border m-4">' .
            '<div class="col-md-1">' . '<img src="' . $friendData->getPicture() . '" alt="User Picture" class="img-size"/></div>' .
            '<div class="col-md-2"><h6>Name</h6>' . $friendData->getFirstName() . ' ' . $friendData->getLastName() . '</div>' .
            '<div class="col-md-2"><h6>Username</h6>' . $friendData->getUsername() . '</div>' .
            '<div id="break" class="col-md-1"><h6>Gender</h6>' . $friendData->getGender() . '</div>' .
            '<div id="break" class="col-md-2"><h6>email</h6>' . $friendData->getEmail() . '</div>' .
            '<div class="col-md-2"><h6>Co-ordinates</h6>' . '<p>' . $friendData->getLongitude() . '</p>' . $friendData->getLatitude() . '</div>' .
            '<div class="col-md-2"><h6>Status</h6><p>Friends</p><form action="'?><?php echo $_SERVER['PHP_SELF']; ?>
        <?php echo '" method="post"><button type="submit" name="unfriend" value="' . $friendData->getUserID() . '" id="btnA" class="btn btn-dark">Unfriend</button></form></div>
                </div>';
    }
} ?>
<p id="testfriends"></p>
    <div id="friend-map" style="width:800px;height:600px; border: black"></div>
    <script src="OpenLayers-2.13.1/OpenLayers.js"></script>
    <script src="/js/httprequest.js"></script>
    <script src="/js/friendMap.js"></script>
    <script src="/js/userpostition.js"></script>


<?php require('template/footer.phtml') ?>