<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="css/bootstrap-theme.css" rel="stylesheet">
    <link href="css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">



<div class="container" >
        <div  class="row">
            <div  class="col-xs-6 col-sm-9 col-md-12">
<!--                <h1>Friend Finder</h1>-->
                    <img class="img" src="images/banner.png" alt="Salford University" />


            </div>
        </div>


    <div class="row">
<!-- nav bar, some options set to only display if user is logged in -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" >
            <div class="container-fluid">
                <ul class="navbar-nav">
                    <li class="nav-item flex-sm-column"><a class="nav-link active" href="index.php">Home</a></li>
                    <?php if(isset($_SESSION["login"])){echo '<li class="nav-item flex-sm-column"><a class="nav-link" href="friends.php">Friends</a></li>';}?>
                    <?php if(isset($_SESSION["login"])){echo '<li class="nav-item flex-sm-column"><a class="nav-link" href="friendRequests.php">Friend Requests</a></li>';}?>
                    <?php if(isset($_SESSION["login"])){echo '<li class="nav-item flex-sm-column"><a class="nav-link" href="findfriends.php">Find Friends</a></li>';}?>
                    <li class="nav-item flex-sm-column"><a class="nav-link" href="search.php">Search Users</a></li>
                    <?php if(!isset($_SESSION["login"])){echo '<li class="nav-item flex-sm-column"><a class="nav-link" href="register.php">Register</a></li>';}?>
                </ul>
                <?php

                if (!isset($_SESSION["login"])) {
                    //displays if user not logged in
                    echo ' 
                    <form method="post" action="' .  $_SERVER['PHP_SELF'] . '" class="form text-success">
                        <label for="username">Username</label>
                        <input type="text" name="username" value="'?><?php if (isset($_COOKIE['username'])) {echo $_COOKIE['username'];} ?><?php echo'">
                        <label for="password">Password</label>
                        <input type="password" name="password">
                        <input type="submit" name="loginbtn" value="Login" class="btn btn-primary">
        
                    </form>';
                }
                else
                {
                    //displays logout button and name if user logged in
                    echo '
            <form method="post" action="' .  $_SERVER['PHP_SELF'] . '" class="form text-primary">
                <label for="logoutbtn">Welcome '. $_SESSION["login"] .'</label>
                <input type="submit" name="logoutbtn" value="Logout" class="btn btn-primary">
            </form>';
                }
                ?>
            </div>
        </nav>
        <?php
        //generates token for use when querying database
        $token = substr(str_shuffle(MD5(microtime())), 0, 15); //random string generation

        $_SESSION["queryToken"] = $token;
        ?>
        <script>
            //sets token for use in javascript classes
            var token = "<?php echo $token ?>";

        </script>
        <?php
        //set global variables from sessions, required in javascript functions
        if(isset($_SESSION["login"]))
        { echo "<script> var loggedIn = true</script>";}
        else {echo "<script> var loggedIn = false</script>";}

        if (isset($_SESSION["userID"]))
        { echo "<script> var userID = " . $_SESSION["userID"] . "</script>";}
        else {echo "<script> var userID = ''</script>";}

        if (isset($_SESSION["username"]))
        { echo "<script> var username = '" . $_SESSION["username"] . "'</script>";}
        else {echo "<script> var username = ' '</script>";}

        ?>




    <div id="content" class="col-xs-6 col-sm-9 col-md-12" >
        <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>



